I18 make this work with error codes
vkamiansky/results pull request #21
Opened 2020-04-05 14:05 UTC by TheSonOfDeimos

Closes #18

2020-04-05 18:16 UTC, vkamiansky requested changes
Suggested review of `Bind` and `BindAsync` for default code overload.

2020-04-05 18:16 UTC, vkamiansky commented on src/Fls.Results/OperationResult.cs
> +        public static async Task<IOperationResult<T>> BindErrorAsync<T>(this IOperationResult<T> source, Func<string, Task<IOperationResult<T>>> bind, Func<Exception, string> getMessage)
These functions here look like special cases of  `public static async Task<IOperationResult<T>> BindErrorAsync<T>(this IOperationResult<T> source, Func<int?, string, Task<IOperationResult<T>>> bind, Func<Exception, string> getMessage, int? exceptionCode = null)`. Can't we make use of them?

2020-04-05 18:40 UTC, TheSonOfDeimos commented on src/Fls.Results/OperationResult.cs
> +        public static async Task<IOperationResult<T>> BindErrorAsync<T>(this IOperationResult<T> source, Func<string, Task<IOperationResult<T>>> bind, Func<Exception, string> getMessage)
Of course, we can use 
```C#
public static async Task<IOperationResult<T>> BindErrorAsync<T>(this IOperationResult<T> source, Func<int?, string, Task<IOperationResult<T>>> bind, Func<Exception, string> getMessage, int? exceptionCode = null)
```
but such signature makes us to define addtional empty parametr in delegate, like 
```C#
BindErrorAsync(
                (_, message) =>
                {
                    return IOperationResult<T>();
                },

                exception =>
                {
                    return default(string);
                }
            );
```

But with overloading, there is no need in fictitious parameter like here
```C#
BindErrorAsync(
                message =>
                {
                    return IOperationResult<T>();
                },

                exception =>
                {
                    return default(string);
                }
            );
```

2020-04-05 18:42 UTC, TheSonOfDeimos commented on src/Fls.Results/OperationResult.cs
> +        public static async Task<IOperationResult<T>> BindErrorAsync<T>(this IOperationResult<T> source, Func<string, Task<IOperationResult<T>>> bind, Func<Exception, string> getMessage)
вп

2020-04-05 18:47 UTC, TheSonOfDeimos commented on src/Fls.Results/OperationResult.cs
> +        public static async Task<IOperationResult<T>> BindErrorAsync<T>(this IOperationResult<T> source, Func<string, Task<IOperationResult<T>>> bind, Func<Exception, string> getMessage)
Also, if we have to support old `Bind` and `BindAsync` signatures, why don't we have to support old signatures of delegates?

2020-04-05 19:20 UTC, vkamiansky requested changes
Just need some simplification.

2020-04-05 19:20 UTC, vkamiansky commented on src/Fls.Results/OperationResult.cs
> +        public static async Task<IOperationResult<T>> BindErrorAsync<T>(this IOperationResult<T> source, Func<string, Task<IOperationResult<T>>> bind, Func<Exception, string> getMessage)
No worries. All I mean is that this method can be implemented as follows:
```c#
public static IOperationResult<T> BindError<T>(this IOperationResult<T> source, 
    Func<string, IOperationResult<T>> bind, 
    Func<Exception, string> getMessage)
    {
        return source.BindError((_, error) => bind(error), getMessage);
    }
```

Arguably, the same applies to other methods with 'no error code' signatures.

2020-04-05 21:14 UTC, TheSonOfDeimos commented on src/Fls.Results/OperationResult.cs
> +        public static async Task<IOperationResult<T>> BindErrorAsync<T>(this IOperationResult<T> source, Func<string, Task<IOperationResult<T>>> bind, Func<Exception, string> getMessage)
Oh, you're right, that looks better

2020-04-05 22:25 UTC, vkamiansky requested changes
Almost there. Just walk through the .cs files with Alt+Shift+F to fix the formatting.

2020-04-06 08:31 UTC, vkamiansky approved these changes
Ready to merge.

2020-04-06 08:42 UTC, merged