WIP i2 add unit tests for all functions
vkamiansky/results pull request #8
Opened 2020-03-07 14:03 UTC by TheSonOfDeimos

Related #2

2020-03-07 15:10 UTC, vkamiansky requested changes
There are 3 `BindAsync` methods. This one is covered. We need the remaining two covered as well.

2020-03-07 15:14 UTC, TheSonOfDeimos commented
It's not complete yet. Here is a pull request with WIP tag

2020-04-01 09:43 UTC, vkamiansky requested changes
We might want our method names more telling.

2020-04-01 09:43 UTC, vkamiansky commented on src/Fls.Results.Test/ResultFunctionsTests.cs
> +        public async void BindAsyncTest_1()
Suppose one of these tests fails and the output says 'BindAsyncTest_1 failed' how do I make out what scenario isn't working. Make test names say in their names what they mean to test and don't be afraid of long names, just of the meaningless ones.

2020-04-01 09:43 UTC, vkamiansky commented on src/Fls.Results.Test/ResultFunctionsTests.cs
> +        public async void BindAsyncTest_2()
Name change suggested.

2020-04-01 09:43 UTC, vkamiansky commented on src/Fls.Results.Test/ResultFunctionsTests.cs
> +        public async void BindAsyncTest_3()
Name change suggested.

2020-04-01 12:51 UTC, vkamiansky approved these changes

2020-04-01 17:23 UTC, merged